version: '3.3'

services:
  prueba:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
  app:
    container_name: app
    depends_on:
      - prueba
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 8000:8000
      - 9229:9229

